version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/api/Dockerfile

  pgserver:
    container_name: airbooking_postgres
    hostname: airbooking
    image: postgres:latest
    restart: unless-stopped  
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: airbooking_db

  pgadmin:
    container_name: airbooking_pgAdmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: app
    ports:
      - "5050:80"
    volumes:
       - ./pgAdmin/pgAdmin:/var/lib/pgadmin
       - ./pgAdmin/pgAdmin_storage:/var/lib/pgadmin/storage/
    depends_on:
      - pgserver